// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalRLiveGrid.Data;

namespace SignalRLiveGrid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200623070822_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignalRLiveGrid.Data.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsLock");

                    b.Property<string>("Name");

                    b.Property<decimal>("Salary");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            IsLock = false,
                            Name = "John",
                            Salary = 10m
                        },
                        new
                        {
                            PersonId = 2,
                            IsLock = false,
                            Name = "Logan",
                            Salary = 20m
                        },
                        new
                        {
                            PersonId = 3,
                            IsLock = false,
                            Name = "James",
                            Salary = 30m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
